#!/bin/bash
#nohup ./run/depparser-arceager-en-uearly-aap-b64-c01.sh     > log/`date +%Y-%m-%d-%H%M%S`.depparser-arceager-en-uearly-aap-b64-c01.log &
#nohup ./run/depparser-arceager-en-uearly-aap-b64-c16.sh     > log/`date +%Y-%m-%d-%H%M%S`.depparser-arceager-en-uearly-aap-b64-c16.log &
#nohup ./run/depparser-arceager-en-umax-aap-b64-c01.sh      > log/`date +%Y-%m-%d-%H%M%S`.depparser-arceager-en-umax-aap-b64-c01.log &
#nohup ./run/depparser-arceager-en-umax-aap-b64-c16.sh      > log/`date +%Y-%m-%d-%H%M%S`.depparser-arceager-en-umax-aap-b64-c16.log &
#nohup ./run/en-arceager-depparser.sh                       > log/`date +%Y-%m-%d-%H%M%S`.en-arceager-depparser.log &
#nohup ./run/en-arceager-depparser-minibatch.sh             > log/`date +%Y-%m-%d-%H%M%S`.en-arceager-depparser-minibatch.log &
#nohup ./run/wsj-postagger.sh                               > log/`date +%Y-%m-%d-%H%M%S`.wsj-postagger.log &
#nohup ./run/seqlabeler-conll2000.sh                        > log/`date +%Y-%m-%d-%H%M%S`.seqlabeler-conll2000.log &
#nohup ./run/seqlabeler-semchunk-ch-uearly-aap-b64-c01-n0.sh > log/`date +%Y-%m-%d-%H%M%S`.seqlabeler-semchunk-ch-uearly-aap-b64-c01-n0.log &
#nohup ./run/seqlabeler-semchunk-ch-uearly-aap-b64-c16-n0.sh > log/`date +%Y-%m-%d-%H%M%S`.seqlabeler-semchunk-ch-uearly-aap-b64-c16-n0.log &
#nohup ./run/seqlabeler-semchunk-ch-uearly-aap-b64-c01-n1.sh > log/`date +%Y-%m-%d-%H%M%S`.seqlabeler-semchunk-ch-uearly-aap-b64-c01-n1.log &
#nohup ./run/seqlabeler-semchunk-ch-uearly-aap-b64-c16-n1.sh > log/`date +%Y-%m-%d-%H%M%S`.seqlabeler-semchunk-ch-uearly-aap-b64-c16-n1.log &
#nohup ./run/seqlabeler-semchunk-ch-umax-aap-b64-c01-n0.sh > log/`date +%Y-%m-%d-%H%M%S`.seqlabeler-semchunk-ch-umax-aap-b64-c01-n0.log &
#nohup ./run/seqlabeler-semchunk-ch-umax-aap-b64-c16-n0.sh > log/`date +%Y-%m-%d-%H%M%S`.seqlabeler-semchunk-ch-umax-aap-b64-c16-n0.log &
#nohup ./run/seqlabeler-semchunk-ch-umax-aap-b64-c01-n1.sh > log/`date +%Y-%m-%d-%H%M%S`.seqlabeler-semchunk-ch-umax-aap-b64-c01-n1.log &
#nohup ./run/seqlabeler-semchunk-ch-umax-aap-b64-c16-n1.sh > log/`date +%Y-%m-%d-%H%M%S`.seqlabeler-semchunk-ch-umax-aap-b64-c16-n1.log &
#nohup ./run/seqlabeler-semchunk-en-uearly-aap-b64-c01-n0.sh > log/`date +%Y-%m-%d-%H%M%S`.seqlabeler-semchunk-en-uearly-aap-b64-c01-n0.log &
#nohup ./run/seqlabeler-semchunk-en-uearly-aap-b64-c16-n0.sh > log/`date +%Y-%m-%d-%H%M%S`.seqlabeler-semchunk-en-uearly-aap-b64-c16-n0.log &
#nohup ./run/seqlabeler-semchunk-en-umax-aap-b64-c01-n0.sh > log/`date +%Y-%m-%d-%H%M%S`.seqlabeler-semchunk-en-umax-aap-b64-c01-n0.log &
#nohup ./run/seqlabeler-semchunk-en-umax-aap-b64-c16-n0.sh > log/`date +%Y-%m-%d-%H%M%S`.seqlabeler-semchunk-en-umax-aap-b64-c16-n0.log &
#nohup ./run/seqlabeler-semchunk-en-umax-aap-b64-c01-n1.sh > log/`date +%Y-%m-%d-%H%M%S`.seqlabeler-semchunk-en-umax-aap-b64-c01-n1.log &
#nohup ./run/seqlabeler-semchunk-en-umax-aap-b64-c16-n1.sh > log/`date +%Y-%m-%d-%H%M%S`.seqlabeler-semchunk-en-umax-aap-b64-c16-n1.log &
#nohup ./run/mono_srl.sh                                > log/`date +%Y-%m-%d-%H%M%S`.mono_srl.log &
