var searchData=
[
  ['encode',['encode',['../classZuoPar_1_1Engine_1_1TokenAlphabet.html#abe61ae77ce117db13039c854c50533f7',1,'ZuoPar::Engine::TokenAlphabet::encode(const char *name) const '],['../classZuoPar_1_1Engine_1_1TokenAlphabet.html#ac3b9af097b6c47b79dab663a1a58b7a8',1,'ZuoPar::Engine::TokenAlphabet::encode(const std::string &amp;name) const ']]],
  ['end',['end',['../classZuoPar_1_1IO_1_1BlockIterator.html#afbd0fbcbeefb4ec61224a37020841ec8',1,'ZuoPar::IO::BlockIterator']]],
  ['errors',['errors',['../classZuoPar_1_1OnlineLearner.html#aec8ae4e3d0c1c44dac30b28e84c75950',1,'ZuoPar::OnlineLearner::errors()'],['../classZuoPar_1_1TransitionStructureOnlineLearner.html#a478d4ea90553c8a89237b6d21a7e8f35',1,'ZuoPar::TransitionStructureOnlineLearner::errors()']]],
  ['evaluate_5fchen14ch',['evaluate_chen14ch',['../classZuoPar_1_1DependencyParser_1_1DependencyParserUtils.html#ac7c10589a0dc7c83f80badba631fd3c5',1,'ZuoPar::DependencyParser::DependencyParserUtils::evaluate_chen14ch(const std::vector&lt; std::string &gt; &amp;forms, const std::vector&lt; std::string &gt; &amp;postags, const HeadListType &amp;predicted_heads, const HeadListType &amp;heads, bool dummy)'],['../classZuoPar_1_1DependencyParser_1_1DependencyParserUtils.html#a0b64edd423a9f1aa175fa3d3747b5cc5',1,'ZuoPar::DependencyParser::DependencyParserUtils::evaluate_chen14ch(const std::vector&lt; std::string &gt; &amp;forms, const std::vector&lt; std::string &gt; &amp;postags, const HeadListType &amp;predicted_heads, const DeprelListType &amp;predicted_deprels, const HeadListType &amp;heads, const DeprelListType &amp;deprels, bool dummy)'],['../classZuoPar_1_1DependencyParser_1_1DependencyParserUtils.html#af9382fbb34216bfa7a42c0a69a4eaee8',1,'ZuoPar::DependencyParser::DependencyParserUtils::evaluate_chen14ch(const RawCoNLLXDependency &amp;data, const std::vector&lt; int &gt; &amp;heads, const std::vector&lt; std::string &gt; &amp;deprels)']]],
  ['evaluate_5fchen14en',['evaluate_chen14en',['../classZuoPar_1_1DependencyParser_1_1DependencyParserUtils.html#a3bda559499c0a4dffe63b894ecca6f85',1,'ZuoPar::DependencyParser::DependencyParserUtils::evaluate_chen14en(const std::vector&lt; std::string &gt; &amp;forms, const std::vector&lt; std::string &gt; &amp;postags, const HeadListType &amp;predicted_heads, const HeadListType &amp;heads, bool dummy)'],['../classZuoPar_1_1DependencyParser_1_1DependencyParserUtils.html#a376bd23cd9e1f97bfd3519021dad1b9b',1,'ZuoPar::DependencyParser::DependencyParserUtils::evaluate_chen14en(const std::vector&lt; std::string &gt; &amp;forms, const std::vector&lt; std::string &gt; &amp;postags, const HeadListType &amp;predicted_heads, const DeprelListType &amp;predicted_deprels, const HeadListType &amp;heads, const DeprelListType &amp;deprels, bool dummy)'],['../classZuoPar_1_1DependencyParser_1_1DependencyParserUtils.html#aae7f953f67daa7858790a7771561b16e',1,'ZuoPar::DependencyParser::DependencyParserUtils::evaluate_chen14en(const RawCoNLLXDependency &amp;data, const std::vector&lt; int &gt; &amp;heads, const std::vector&lt; std::string &gt; &amp;deprels)']]],
  ['evaluate_5fconllx',['evaluate_conllx',['../classZuoPar_1_1DependencyParser_1_1DependencyParserUtils.html#aea02879c4a3d4885a078c0ae907a5e81',1,'ZuoPar::DependencyParser::DependencyParserUtils::evaluate_conllx(const std::vector&lt; std::string &gt; &amp;forms, const std::vector&lt; std::string &gt; &amp;postags, const HeadListType &amp;predicted_heads, const HeadListType &amp;heads, bool dummy)'],['../classZuoPar_1_1DependencyParser_1_1DependencyParserUtils.html#ade24e1182568a70f7d033d60614858a3',1,'ZuoPar::DependencyParser::DependencyParserUtils::evaluate_conllx(const std::vector&lt; std::string &gt; &amp;forms, const std::vector&lt; std::string &gt; &amp;postags, const HeadListType &amp;predicted_heads, const DeprelListType &amp;predicted_deprels, const HeadListType &amp;heads, const DeprelListType &amp;deprels, bool dummy)'],['../classZuoPar_1_1DependencyParser_1_1DependencyParserUtils.html#a8911f7da72d9f1ac0089c278c4d582f7',1,'ZuoPar::DependencyParser::DependencyParserUtils::evaluate_conllx(const RawCoNLLXDependency &amp;data, const std::vector&lt; int &gt; &amp;heads, const std::vector&lt; std::string &gt; &amp;deprels)']]],
  ['evaluate_5finc_5fpunc',['evaluate_inc_punc',['../classZuoPar_1_1DependencyParser_1_1DependencyParserUtils.html#ae294b3c589e36eee57f8e3092999c855',1,'ZuoPar::DependencyParser::DependencyParserUtils::evaluate_inc_punc(const std::vector&lt; std::string &gt; &amp;forms, const std::vector&lt; std::string &gt; &amp;postags, const HeadListType &amp;predicted_heads, const HeadListType &amp;heads, bool dummy)'],['../classZuoPar_1_1DependencyParser_1_1DependencyParserUtils.html#a00156fd07b3fcb6657ae051b6dfeace5',1,'ZuoPar::DependencyParser::DependencyParserUtils::evaluate_inc_punc(const std::vector&lt; std::string &gt; &amp;forms, const std::vector&lt; std::string &gt; &amp;postags, const HeadListType &amp;predicted_heads, const DeprelListType &amp;predicted_deprels, const HeadListType &amp;heads, const DeprelListType &amp;deprels, bool dummy)']]],
  ['execute',['execute',['../classZuoPar_1_1TransitionStructureOnlineLearner.html#a49ae8d3601646d28348c24bfa078dc78',1,'ZuoPar::TransitionStructureOnlineLearner']]],
  ['extend_5fcandidate_5ftransition',['extend_candidate_transition',['../classZuoPar_1_1TransitionSystem.html#a8ea6674423f6eaed1e6d0f94e5902d4c',1,'ZuoPar::TransitionSystem']]],
  ['extractor',['Extractor',['../classZuoPar_1_1DependencyParser_1_1NeuralNetwork_1_1Extractor.html#af9fdc419d705b44981ccc20d7c409d7b',1,'ZuoPar::DependencyParser::NeuralNetwork::Extractor']]]
];
