#ifndef __ZUOPAR_APP_DEPPARSER_ARCSTANDARD_LEARN_H__
#define __ZUOPAR_APP_DEPPARSER_ARCSTANDARD_LEARN_H__

int learn(int argc, char** argv);

#endif  //  end for __ZUOPAR_APP_DEPPARSER_ARCSTANDARD_LEARN_H__

