#include "app/lexanalyzer/postagger/weight.h"

namespace ZuoPar {
namespace LexicalAnalyzer {
namespace Postagger {

Weight::Weight() {
  ZUOPAR_FEATURE_MAP_REGIST_S0( W0 );
  ZUOPAR_FEATURE_MAP_REGIST_S0( W1 );
  ZUOPAR_FEATURE_MAP_REGIST_S0( W2 );
  ZUOPAR_FEATURE_MAP_REGIST_S0( W_1 );
  ZUOPAR_FEATURE_MAP_REGIST_S0( W_2 );
  ZUOPAR_FEATURE_MAP_REGIST_S1( PRE1 );
  ZUOPAR_FEATURE_MAP_REGIST_S1( PRE2 );
  ZUOPAR_FEATURE_MAP_REGIST_S1( PRE3 );
  ZUOPAR_FEATURE_MAP_REGIST_S1( PRE4 );
  ZUOPAR_FEATURE_MAP_REGIST_S1( SUF1 );
  ZUOPAR_FEATURE_MAP_REGIST_S1( SUF2 );
  ZUOPAR_FEATURE_MAP_REGIST_S1( SUF3 );
  ZUOPAR_FEATURE_MAP_REGIST_S1( SUF4 );
  ZUOPAR_FEATURE_MAP_REGIST_U0( NUM );
  ZUOPAR_FEATURE_MAP_REGIST_U0( UPPERCASE );
  ZUOPAR_FEATURE_MAP_REGIST_U0( HYPHEN );
  ZUOPAR_FEATURE_MAP_REGIST_U0( T_1 );
  ZUOPAR_FEATURE_MAP_REGIST_B00( T_2, T_1 );
}

} //  namespace postagger
} //  namespace lexicalanalyzer
} //  namespace zuopar
